kind: Template
apiVersion: v1
metadata:
  annotations:
    tags: knative
  name: knative2
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
   name: "${NAMESPACE_KNATIVE}"
- apiVersion: serving.knative.dev/v1alpha1
  kind: KnativeServing
  metadata:
    name: knative-serving
    namespace: "${NAMESPACE_KNATIVE}"
  spec:
    config:
      autoscaler:
        container-concurrency-target-default: '100'
        container-concurrency-target-percentage: '1.0'
        enable-scale-to-zero: 'true'
        max-scale-up-rate: '10'
        panic-threshold-percentage: '200.0'
        panic-window: 6s
        panic-window-percentage: '10.0'
        scale-to-zero-grace-period: 30s
        stable-window: 60s
        tick-interval: 2s
      defaults:
        revision-cpu-limit: 1000m
        revision-cpu-request: 400m
        revision-memory-limit: 200M
        revision-memory-request: 100M
        revision-timeout-seconds: '300'
      deployment:
        registriesSkippingTagResolving: 'ko.local,dev.local'
      gc:
        stale-revision-create-delay: 24h
        stale-revision-lastpinned-debounce: 5h
        stale-revision-minimum-generations: '1'
        stale-revision-timeout: 15h
      logging:
        loglevel.activator: info
        loglevel.autoscaler: info
        loglevel.controller: info
        loglevel.queueproxy: info
        loglevel.webhook: info
      observability:
        logging.enable-var-log-collection: 'false'
        metrics.backend-destination: prometheus
      tracing:
        backend: none
        sample-rate: '0.1'
parameters:
  - name: NAMESPACE_KNATIVE
    displayName: Namespace for KNATIVE
    description: Namespace for KNATIVE
    required: true
